[package]
name = "bq25616"
version = "0.1.0"
description = "GPIO control for the TI BQ25616 standalone battery charger, with a typed active-low charge enable"
readme = "README.md"
publish = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true

[dev-dependencies]
embedded-hal-mock.workspace = true

[lints]
workspace = true
